tasks:
  - name: InstallCdkCli
    before: |
      ./bin/install-cdk-cli.sh
  - name: InstallTerraformCli
    before: |
      ./bin/install-terraform-cli.sh
  - name: Utils
    before: |
      ./bin/install-utils.sh
  - name: InstallAwsCli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/install-aws-cli.sh
