tasks:
  - name: utils
    before: |
      sudo apt-get install tree
  # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
  - name: InstallAwsCli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $GITPOD_REPO_ROOT
