#!/usr/bin/env bash

echo "create bucket"

if [ -z "$1" ]; then
    echo "Please provide a bucket name. eg: ./bucket my-bucket"
    exit 1 
fi

BUCKET_NAME=$1
# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration LocationConstraint=ap-south-1 \
--query Location \
--output text