#!/usr/bin/env bash

echo "delete bucket"

if [ -z "$1" ]; then
    echo "Please provide a bucket name. eg: ./bucket my-bucket"
    exit 1 
fi

BUCKET_NAME=$1

aws s3api delete-bucket \
--bucket $BUCKET_NAME