#!/usr/bin/env bash

echo "delete objects"

if [ -z "$1" ];then
    echo "Please provide a bucket name. eg: ./bucket my-bucket"
    exit 1
fi

BUCKET_NAME=$1
# https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-objects.html
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key | jq '{Objects: map({Key: .})}' > /tmp/delete_objects.json

aws s3api delete-objects \
--bucket $BUCKET_NAME \
--delete file:///tmp/delete_objects.json