#!/usr/bin/env bash

if [ -z "$1" ];then
    echo "Please provide a bucket name. eg: ./bucket my-bucket"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key